name: country
description: ISO 3166-1 Coutry codes
version: 0.0.1
author: Denis Portnov <denixport@gmail.com>

environment:
  sdk: '>=2.1.0 <3.0.0'

#dependencies:
#  path: ^1.4.1

dev_dependencies:
  pedantic: ^1.0.0
  test: ^1.0.0
